Feature/landing page
LitopiaCommunity/LitopiaFrontS5 pull request #2
Opened 2021-09-04 06:44 UTC by mrsolarius

# Features
* Mise en place d'une navbar pleine page comme indiquer dans le proto figma
* Création d'animation de hover
* Mise en place d'une version responsive avec une navbar en bas et une top bar en haut
* Création d'animation de hover sur la version mobile

2021-09-04 06:50 UTC, mrsolarius reviewed
Normalement pour moi tous est bon, mais après, c’est moi et Rehark qui l'avons fait donc forcément xD

2021-09-04 07:44 UTC, improvkardi requested changes

2021-09-04 07:44 UTC, improvkardi commented on src/stylesheets/components/navbars.scss
> +          font-size: 10px!important;
Important sur une taille de police ?

2021-09-04 07:51 UTC, mrsolarius commented on src/stylesheets/components/navbars.scss
> +          font-size: 10px!important;
J'ai réglé le souci par contre, c’est un peu plus long qu’avant

2021-09-04 18:48 UTC, improvkardi approved these changes

2021-09-05 16:17 UTC, mrsolarius reviewed
C'est toujours ok pour moi avec le code de rehark en plus

2021-09-08 17:30 UTC, jojojojojota approved these changes

2021-09-08 17:31 UTC, merged